Front/Controllers/BillController.cs
using Back.Models;
using Front.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Text;
using System.Text.Json;
using static Back.Models.Bill;
using static Back.Models.Parametric;
using static Back.Models.Reply;

namespace Front.Controllers
{
    public class BillController : Controller
    {
        private readonly ILogger<BillController> _logger;
        string api = "https://localhost:7228/";
        public BillController(ILogger<BillController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<object> GetClients()
        {
            // Crear una instancia de HttpClient
            using (HttpClient client = new HttpClient())
            {
                try
                {
                    ReplyLogin reply = new ReplyLogin();
                    List<DefaultClass> clients = new List<DefaultClass>();
                    // Hacer una solicitud GET a la API externa
                    HttpResponseMessage response = await client.GetAsync(api + "api/GetClients");

                    // Verificar si la solicitud fue exitosa
                    if (response.IsSuccessStatusCode)
                    {
                        // Leer el contenido de la respuesta
                        string jsonString = await response.Content.ReadAsStringAsync();

                        // Convierte la respuesta JSON a un objeto
                        reply  = JsonConvert.DeserializeObject<ReplyLogin>(jsonString);
                        clients = JsonConvert.DeserializeObject<List<DefaultClass>>(reply.Data.ToString());

                    }
                    return clients;
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
        }

        public async Task<object> GetProducts()
        {
            // Crear una instancia de HttpClient
            using (HttpClient client = new HttpClient())
            {
                try
                {
                    ReplyLogin reply = new ReplyLogin();
                    List<Products> Products = new List<Products>();
                    // Hacer una solicitud GET a la API externa
                    HttpResponseMessage response = await client.GetAsync(api + "api/GetProducts");

                    // Verificar si la solicitud fue exitosa
                    if (response.IsSuccessStatusCode)
                    {
                        // Leer el contenido de la respuesta
                        string jsonString = await response.Content.ReadAsStringAsync();

                        // Convierte la respuesta JSON a un objeto
                        reply = JsonConvert.DeserializeObject<ReplyLogin>(jsonString);
                        Products = JsonConvert.DeserializeObject<List<Products>>(reply.Data.ToString());

                    }
                    return Products;
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
        }

        [HttpPost]
        public async Task<object> SaveBill([FromBody] BillModel data)
        {
            // Crear una instancia de HttpClient
            using (HttpClient client = new HttpClient())
            {
                try
                {
                    ReplyLogin reply = new ReplyLogin();
                    var json = Newtonsoft.Json.JsonConvert.SerializeObject(data);

                    // URL del servicio externo
                    var urlServicio = api + "api/SaveBill";

                    // Crear la solicitud POST al servicio externo
                    var content = new StringContent(json, Encoding.UTF8, "application/json");

                    // Realizar la solicitud POST al servicio externo
                    var response = await client.PostAsync(urlServicio, content);

                    // Verificar si la solicitud fue exitosa
                    if (response.IsSuccessStatusCode)
                    {
                        // Leer la respuesta del servicio
                        string jsonString = await response.Content.ReadAsStringAsync();

                        // Convierte la respuesta JSON a un objeto
                        reply = JsonConvert.DeserializeObject<ReplyLogin>(jsonString);
                        return reply.Flag;
                    }
                    else
                    {
                        // Manejar la respuesta si la solicitud no fue exitosa
                        return false;
                    }
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
        }


    }
}

Front/Controllers/SearchBillController.cs
using Front.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using static Back.Models.Bill;
using static Back.Models.Reply;
using System.Text;
using static Back.Models.Parametric;

namespace Front.Controllers
{
    public class SearchBillController : Controller
    {
        private readonly ILogger<SearchBillController> _logger;
        string api = "https://localhost:7228/";

        public SearchBillController(ILogger<SearchBillController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<object> GetBills([FromBody] BillFilter data)
        {
            // Crear una instancia de HttpClient
            using (HttpClient client = new HttpClient())
            {
                try
                {
                    List<BillFound> Bills = new List<BillFound>();
                    ReplyLogin reply = new ReplyLogin();
                    var json = Newtonsoft.Json.JsonConvert.SerializeObject(data);

                    // URL del servicio externo
                    var urlServicio = api + "api/GetBills";

                    // Crear la solicitud POST al servicio externo
                    var content = new StringContent(json, Encoding.UTF8, "application/json");

                    // Realizar la solicitud POST al servicio externo
                    var response = await client.PostAsync(urlServicio, content);

                    // Verificar si la solicitud fue exitosa
                    if (response.IsSuccessStatusCode)
                    {
                        // Leer la respuesta del servicio
                        string jsonString = await response.Content.ReadAsStringAsync();

                        // Convierte la respuesta JSON a un objeto
                        reply = JsonConvert.DeserializeObject<ReplyLogin>(jsonString);
                        Bills = JsonConvert.DeserializeObject<List<BillFound>>(reply.Data.ToString());
                        
                    }
                    return Bills;
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
        }

    }
}

Front/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Front</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Front.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn3.devexpress.com/jslib/23.1.6/css/dx.light.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn3.devexpress.com/jslib/23.1.6/js/dx.all.js"></script>
    <script src="https://kit.fontawesome.com/4a70a8dc5b.js" crossorigin="anonymous"></script>

</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Front</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bill" asp-action="Index">Crear factura</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SearchBill" asp-action="Index">Consultar facturas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>